name: getx_skeleton
version: 1.0.0+1
publish_to: none
description: start your project in the fastest way
environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.5
  get: ^4.6.5 # for state management and context less stuff

  logger: ^1.4.0 # log events in clear way insted of (print)

  flutter_screenutil: ^5.8.4 # make app responsive

  dio: ^5.2.1+1 # for api requests
  pretty_dio_logger: ^1.3.1 # for dio api logging and debugging
  flutter_advanced_drawer: ^1.3.6
  shared_preferences: ^2.2.0 # shared preferences persistence key value store

  firebase_core: ^2.14.0 # to initialize firebase services
  firebase_messaging: ^14.6.4 # fcm services
  awesome_notifications: ^0.7.4+1 # notifications services (will be used for fcm)

  flutter_launcher_icons: # change app icon
  change_app_package_name: # change package name
  rename_app: 1.0.0 # rename app

  flutter_svg:  # display svg vectors

  flutter:
    sdk: flutter

dev_dependencies:
  mockito:
  flutter_lints:

  integration_test:
    sdk: flutter

  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/vectors/
    - assets/fonts/
    - assets/json/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 700
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
          weight: 300
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 900
     #monadi
    - family: Monadi
      fonts:
        - asset: assets/fonts/Monadi.ttf
          #raleway.regular
    - family: Raleway
      fonts:
        - asset: assets/fonts/raleway.regular.ttf
          weight: 300